package sinbad2.valuation.valuationset.listener;

public enum EValuationSetChange {
	NEW_VALUATION, NEW_SEVERAL_VALUATIONS, MODIFY_VALUATION, MODIFY_SEVERAL_VALUATIONS, REMOVE_VALUATION, REMOVE_SEVERAL_VALUATIONS, VALUATIONS_CHANGES;
}
