package sinbad2.valuation.valuationset.listener;

public enum EValuationSetChange {
	NEW_VALUATION, NEW_MULTIPLE_VALUATIONS, MODIFY_VALUATION, MODIFY_MULTIPLE_VALUATIONS, REMOVE_VALUATION, REMOVE_MULTIPLE_VALUATIONS, VALUATIONS_CHANGES;
}
