package sinbad2.element.alternative.listener;

public enum EAlternativesChange {
	ALTERNATIVES_CHANGES, ADD_ALTERNATIVE, ADD_SEVERAL_ALTERNATIVES, REMOVE_ALTERNATIVE, REMOVE_SEVERAL_ALTERNATIVES, MODIFY_ALTERNATIVE
}
