package sinbad2.element.alternative.listener;

public enum EAlternativesChange {
	ALTERNATIVES_CHANGES, ADD_ALTERNATIVE, ADD_MULTIPLE_ALTERNATIVES, REMOVE_ALTERNATIVE, REMOVE_MULTIPLE_ALTERNATIVES, MODIFY_ALTERNATIVE
}
